### ISSUE TITLE
Elytra doesn't move with torso

### ISSUE THREAD

**Issue by Stonewall0210** [Trainguy9512/trainguys-animation-overhaul#1]
Simple as the title:

1. Wear an elytra
2. Walk/Sprint around in 3rd person mode. It's more apparent if you look directly down

Image example 
![2021-08-14_21 29 28](https://user-images.githubusercontent.com/76092465/129444961-2f6df719-a13e-49da-8d81-9aeab0d2d450.png)

I will probably be submitting a lot of bug reports for this mod, but I will try to filter out things that appear to be not worked on. I reported this because armour is effected by the player bobbing but elytra isn't

**Comment by Trainguy9512** [comment]
I haven't touched Elytra stuff yet, but thank you for letting me know! If elytra parenting doesnt happen the same way it happens with armor, it will definitely require some extra work.
