### ISSUE TITLE
Using elytra puts the player in a weird position.

### ISSUE THREAD

**Issue by CROOT-ROM** [Trainguy9512/trainguys-animation-overhaul#10]
It appears that using the elytra puts the player in a permanent falling position. (Kinda looks like an angel pose however, which is cool
![2021-12-05_14 43 34](https://user-images.githubusercontent.com/68515101/144763219-0ba860f1-ff23-43f2-acc6-f84c34d4ef24.png)
)
Video:
https://gfycat.com/flawedcavernousarchaeocete

**Comment by Trainguy9512** [comment]
Fall flying animations aren't in yet, so they're going to look like that until they're implemented
