### ISSUE TITLE
i have this bug in 1.19.3 and idk why is it happening

### ISSUE THREAD

**Issue by ocsmanygeci** [Trainguy9512/trainguys-animation-overhaul#103]
When i join a world both the fps and tps view is bugged out
![2023-01-29_11 22 40](https://user-images.githubusercontent.com/123896415/215347580-d2f8696d-0c0e-468a-b181-989fee5a9f74.png)
![2023-01-29_11 22 35](https://user-images.githubusercontent.com/123896415/215347585-8f32d0eb-d049-4b86-b7a6-7c8987baa193.png)

I tried uninstalling the mod and redoing everything but it still the same

**Comment by S-N00B-1** [comment]
The mod is unfinished. It's not intended for regular use.

**Comment by ocsmanygeci** [comment]
> The mod is unfinished. It's not intended for regular use.

oh okay thanks :)

**Comment by Trainguy9512** [comment]
ye this is just debug testing, no actual animations are ready for use yet
