### ISSUE TITLE
Infinite running on 1.19.3

### ISSUE THREAD

**Issue by MariobrosU22** [Trainguy9512/trainguys-animation-overhaul#105]
I am not sure whats gone wrong, in 3rd person, i am running infinitely, no matter what i do. Always running.
Whats weirder is that in 1st person, i am holding a shield in offhand and stick in main hand while my inventory is empty, and my arms are moving about while holding them. My character does also not change direction at all, they are locked south.
![image](https://user-images.githubusercontent.com/97406208/215584589-4b806da6-9d40-48ba-9053-e487d3c9eceb.png)
![image](https://user-images.githubusercontent.com/97406208/215584647-4c79e72c-fab0-492d-9aff-013cc21c5a93.png)
**MOD LIST**
![image](https://user-images.githubusercontent.com/97406208/215585428-c7bcf39e-1c69-4a84-b6c1-3e206a24ce3b.png)

**Comment by HarperTL** [comment]
have you found a way to resolve this issue as i am having the same one..?

**Comment by MariobrosU22** [comment]
I am glad i am not the only one

**Comment by Woodgoldtwo** [comment]
The mod isn't meant to be used yet

**Comment by Woodgoldtwo** [comment]
https://github.com/Trainguy9512/trainguys-animation-overhaul/issues/103#issuecomment-1407976230

**Comment by MariobrosU22** [comment]
Is there a 1.19.3 stable release yet?

**Comment by Woodgoldtwo** [comment]
the mod is going through a complete rewrite so don't expect stable builds for at least a couple of months

**Comment by MariobrosU22** [comment]
ok thanks
