### ISSUE TITLE
New mod copy on 9 minecraft

### ISSUE THREAD

**Issue by HarperTL** [Trainguy9512/trainguys-animation-overhaul#106]
found another mod copy on 9minecraft made by the same people, image is for their names and here's website link: https://www.9minecraft.net/improved-animations-mod/
![trainguys mod](https://user-images.githubusercontent.com/123916034/215942593-80bd62b3-fc46-46ab-bf46-d83dd3444ba1.JPG)

**Comment by Trainguy9512** [comment]
oh well, i don't even know if it's possible to report things on 9minecraft. no big deal
