### ISSUE TITLE
Cannot Get CurseMaven

### ISSUE THREAD

**Issue by Olinus10** [Trainguy9512/trainguys-animation-overhaul#107]
When building the 1.19.3 experimental version i get this issue preventing the build to be completed:

* What went wrong:
A problem occurred configuring project ':fabric'.
> Could not resolve all files for configuration ':fabric:modRuntimeOnly'.
   > Could not download 3dskinlayers-521480-3541751.jar (curse.maven:3dskinlayers-521480:3541751)
      > Could not get resource 'https://www.cursemaven.com/curse/maven/3dskinlayers-521480/3541751/3dskinlayers-521480-3541751.jar'.
         > Could not GET 'https://www.cursemaven.com/curse/maven/3dskinlayers-521480/3541751/3dskinlayers-521480-3541751.jar'. Received status code 403 from server: Forbidden

**Comment by Trainguy9512** [comment]
the 1.19 experimental version only works on the experimental deep dark snapshot from early 2022, which is technically 1.18.2. i believe this is because this version of the mod does not exist anymore
