### ISSUE TITLE
third person animations are broken

### ISSUE THREAD

**Issue by AlbinoFoxGithub** [Trainguy9512/trainguys-animation-overhaul#110]
using 3rd person animations results in this happening. the character also doesnt rotate when moving and newer versions of the mod dont have 3rd person animations at all
![image](https://user-images.githubusercontent.com/70042305/221691964-91499b75-5790-4e48-9454-f95fdf5138a9.png)

**Comment by xlifi** [comment]
https://github.com/Trainguy9512/trainguys-animation-overhaul/issues/105

**Comment by Trainguy9512** [comment]
this is intentional at the moment
