### ISSUE TITLE
Theres this guy that (almost fixed) the "i suck at gthub how do i download" problem but its not working 

### ISSUE THREAD

**Issue by Jermiahthebuild** [Trainguy9512/trainguys-animation-overhaul#134]
I clicked the link and it just said "failed to generate QR code to download artifact" IDK what to do and also I'm on Xbox Series X.

**Comment by Asad-13** [comment]
Provide more info. What video/guide are you referencing? Give the link, so we can see what exactly is going wrong when you try that.

**Comment by CFog1** [comment]
> I clicked the link and it just said "failed to generate QR code to download artifact" IDK what to do and also I'm on Xbox Series X.

THIS IS MADE FOR PC

**Comment by Yum-Muy** [comment]
yeah, more specifically, java. sorry man.
