### ISSUE TITLE
other animations gone

### ISSUE THREAD

**Issue by EysseW** [Trainguy9512/trainguys-animation-overhaul#14]
I don't know if this is intended, but all other animations are just gone. I don't have flying animations, sword sweeping animations, bow animations, crossbow animations and so on and so forth

**Comment by MerpisMe** [comment]
They haven't been added back yet

**Comment by EysseW** [comment]
Why did you close it? The issue is still there

**Comment by Trainguy9512** [comment]
the whole mod has been rewritten since those animations were ingame, not an issue
