### ISSUE TITLE
optifine caps

### ISSUE THREAD

**Issue by xFedee** [Trainguy9512/trainguys-animation-overhaul#24]
with fabric optifine cape mod i can see optifine cape, it's a very broke
![2022-01-09_23 19 33](https://user-images.githubusercontent.com/87451140/148703387-0d4e15f0-9b33-4408-96e9-047dd8ef741d.png)
n

**Comment by xFedee** [comment]
![2022-01-09_23 21 47](https://user-images.githubusercontent.com/87451140/148703452-993c214e-943e-4943-acef-11517a8444ee.png)

**Comment by xFedee** [comment]
p.s. sorry for my bad english

**Comment by Stonewall0210** [comment]
Which mod are you using? There are multiple of them.

**Comment by Trainguy9512** [comment]
closed via discord-submitted bug report
