### ISSUE TITLE
How do I install the damn mod?

### ISSUE THREAD

**Issue by Protocnic** [Trainguy9512/trainguys-animation-overhaul#52]
There are no discord invites anywhere.

**Comment by YoungSoulluoS** [comment]
https://github.com/Trainguy9512/trainguys-animation-overhaul/actions/runs/2064805759 and install Pollen mod https://minecraft-inside.ru/mods/154942-pollen.html?

**Comment by Protocnic** [comment]
> https://github.com/Trainguy9512/trainguys-animation-overhaul/actions/runs/2064805759 and install Pollen mod https://minecraft-inside.ru/mods/154942-pollen.html?

**Comment by Protocnic** [comment]
thanks @YoungSoulluoS it worked. Altough there's a see through effect no clue what it is and how to fix it.

**Comment by EysseW** [comment]
https://discord.gg/U3TU9UDq
