### ISSUE TITLE
 i am getting this compile "error" error and i can't solve it

### ISSUE THREAD

**Issue by Hippara** [Trainguy9512/trainguys-animation-overhaul#56]
> Task :common:compileJava FAILED
<
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BU─░LD FAILED in 33s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by Hippara** [comment]
help me please

**Comment by DBTDerpbox** [comment]
What java version do you have installed? you can check with `java --version` in the terminal

**Comment by Hippara** [comment]
is 16

**Comment by Hippara** [comment]
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6,

**Comment by DBTDerpbox** [comment]
i see, what branch were you compiling?

**Comment by Hippara** [comment]
1.18 old

**Comment by Hippara** [comment]
never mind install at the s mod

**Comment by DBTDerpbox** [comment]
> never mind install at the s mod

..what do you mean by this? i'm referring to branches in the git sense

**Comment by Hippara** [comment]
> > never mind install at the s mod
> 
> ..what do you mean by this? i'm referring to branches in the git 
i install a action page
