### ISSUE TITLE
Unwanted Upload: FullAmpereGaming 

### ISSUE THREAD

**Issue by PotionSeeker** [Trainguy9512/trainguys-animation-overhaul#67]
Just a heads up: An individual named 'FullAmpereGaming' has just uploaded this mod onto CurseForge as their own mod (https://www.curseforge.com/minecraft/mc-mods/animation-overhaul-1-18-2). The 'fabric.mod.json' still identifies the appropriate authors as 'LizIsTired' 'Trainguy' 'MineToBlend' and most importantly 'Coffee'. I don't know this individual's intentions, but I thought you should know.

**Comment by DBTDerpbox** [comment]
i commented on it, but not much of a surprise it got deleted
![image](https://user-images.githubusercontent.com/65347035/174499306-d2c23233-88c0-456c-8985-e046ea80f12e.png)

there were some other comments before mine got removed, i should of screenshotted them before they were removed as well

**Comment by PotionSeeker** [comment]
Luckily it appears that the situation has been resolved for the time being. Let's hope it stays that way and that the real develops will get the credit they deserve when they are ready to release it in full.
