### ISSUE TITLE
Mod crashed with Create Fabric

### ISSUE THREAD

**Issue by ThatBlueMango** [Trainguy9512/trainguys-animation-overhaul#90]
So the mod keeps crashing with create fabric. It sends this message:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: 
Could not execute entrypoint stage 'main' due to errors, provided by 'create'!

Fabric: 0.14.10-1.18.2
Create Fabric: 1.18.2-0.5.0.e-733
Fabric API: 0.66.0+1.18.2
TAO: 1.0-test27

For why does this happen?

**Comment by GameDokter51** [comment]
Sounds like a problem on Create's end. What mods are you using?

**Comment by ThatBlueMango** [comment]
I've since given up on this effort thanks though for the reply.
