### ISSUE TITLE
Animation Overhaul will it come out on 1 19 2?

### ISSUE THREAD

**Issue by Silver00177** [Trainguy9512/trainguys-animation-overhaul#97]
when will it be released on 1 19 2?

**Comment by Trainguy9512** [comment]
idk, not concerned with porting to specific versions at the moment as i focus on the mod itself- though i see no reason why it wouldn't be ported to 1.19.2 once it's done

**Comment by BadSpookyMob** [comment]
When...

**Comment by BadSpookyMob** [comment]
I just want to be happy in the build with animation overhaul and a bunch of visual mods that are only on this version
